#!/usr/bin/env python3
"""Replace every ticket summary in index.html with the exact Jira text."""
import re, sys

JIRA = {
    "AEP-3311": "[Milestone 1] [BE] Assistant Can Interact With BE Portal Apis / Advisor Data",
    "AEP-3312": "[Milestone 1] System Design and Architecture",
    "AEP-3313": "Eng Spec Is Shared Internally to Feature Channel",
    "AEP-3314": "Eng Spec is Shared to Eng Org",
    "AEP-3315": "Eng Spec is Approved",
    "AEP-3316": "Assistant Eval approach is proposed",
    "AEP-3320": "[BE] Consume MCP django library into the Portal BE",
    "AEP-3321": "[BE] Support listing clients in MCP",
    "AEP-3322": "[BE] Support getting a client in the MCP",
    "AEP-3323": "[BE] Support creating a client in the MCP",
    "AEP-3324": "[BE] Support editing a client in the MCP",
    "AEP-3325": "[BE] Support listing trips in the MCP",
    "AEP-3326": "[BE] Support getting a trip in the MCP",
    "AEP-3327": "[BE] Support creating a trip in the MCP",
    "AEP-3328": "[BE] Support editing a trip in the MCP",
    "AEP-3329": "[BE] Support merging trips in the MCP",
    "AEP-3330": "[AI] Hook up Assistant Agent to BE MCP",
    "AEP-3331": "[AI] Authenticate BE MCP Requests",
    "AEP-3332": "[Milestone 1] [AI] [FE] Advisor can chat with the Assistant Agent",
    "AEP-3333": "[Milestone 3] Advisor can add images to the assistant agent prompts",
    "AEP-3334": "[Milestone 1] [AI] [FE] Advisor can see their conversation history",
    "AEP-3335": "[AI] Add system prompts to the Assistant Agent to know how to use BE MCP",
    "AEP-3336": "[AI] Create the DB table",
    "AEP-3337": "[AI] Create the Agent loop",
    "AEP-3338": "[AI] Create the POST /conversation/",
    "AEP-3339": "[AI] Authentication middleware for assistant agent endpoints",
    "AEP-3340": "[Milestone 1] [AI] [FE] Advisor can see all messages in a conversation",
    "AEP-3341": "[AI] Implement GET /conversations/{id} api for advisor",
    "AEP-3342": "[FE] Support loading a conversation from the GET conversation endpoint",
    "AEP-3343": "[AI] Agent streams text and tool use output to FE",
    "AEP-3344": "[Milestone 1] [FE] Portal Layouts support a right sliding window",
    "AEP-3345": "[FE] Support a right sliding window in the current layouts",
    "AEP-3347": "[FE] Support opening agent with a hotkey",
    "AEP-3348": "[FE] Build input to start and continue a conversation with the Assistant",
    "AEP-3349": "[FE] Read SSEs from the AI Service and populate the assistant window with streaming",
    "AEP-3350": "[Milestone 1] [AI] [FE] Advisor can follow links to portal entities like Trips and Clients in the Assistant",
    "AEP-3351": "[AI] Send PositionalEntityFragment SSEs along with TextFragments",
    "AEP-3352": "[FE] Add plugin to Markdown renderer to insert entity Links",
    "AEP-3356": "[Infra] Set up AI service endpoint for FE env variable on prod",
    "AEP-3357": "[Infra] Set up AI service endpoint for FE env variable on staging",
    "AEP-3358": "[Infra] Set up AI service endpoint for FE env variable on dev",
    "AEP-3359": "[Infra] Set up Auth (BE) JWT public key as AI Service env variable on prod",
    "AEP-3360": "[Infra] Set up Auth (BE) JWT public key as AI Service env variable on staging",
    "AEP-3361": "[Infra] Set up Auth (BE) JWT public key as AI Service env variable on dev",
    "AEP-3362": "[AI] Chat history persists during conversation",
    "AEP-3363": "[Milestone 3] Agent Simulations",
    "AEP-3364": "Research simulations on DeepEval",
    "AEP-3365": "[Milestone 2] We can collect feedback for the Assistant Agent",
    "AEP-3366": "[AI] Add feedback mechanism through API",
    "AEP-3369": "[Milestone 1] [AI] Observability and Cost tracking",
    "AEP-3370": "[AI] Logfire can log activity",
    "AEP-3373": "[BE] Generic file upload is supported (POST v1/files/)",
    "AEP-3374": "[AI Service] Read files from chat input and send with assistant agent query",
    "AEP-3375": "[FE] Upload cloudinary file in chat, upload to BE, and send w/ AI chat",
    "AEP-3376": "[Milestone 3] Improve Assistant Agent Performance with Sophisticated Tooling & Architecture",
    "AEP-3377": "[AI] Add web search to Assistant Tooling",
    "AEP-3378": "[AI] Add Prompt chaining (decompose prompt into steps - checklist agent?)",
    "AEP-3379": "[Milestone 3] Assistant Agent is Aware of Help Center + Training",
    "AEP-3380": "[Placeholder] How do we want to handle this?",
    "AEP-3382": "[FE] Implement chat history views (currently no designs)",
    "AEP-3383": "[AI] Implement GET /conversations endpoint for advisor",
    "AEP-3424": "Agent Evals & Simulations",
    "AEP-3425": "Get MCP working locally (BE, set up Jeff user, & locally run)",
    "AEP-3426": "Add MLflow integration",
    "AEP-3513": "Data models are approved",
    "AEP-3519": "Tasks and Resource allocation",
    "AEP-3549": "[BE] Support profile endpoint in MCP",
    "AEP-3572": "[AI] Costs can be tracked per convo using genai-prices",
    "AEP-3574": "[AI] Add streaming SSE fragments to be used by AEP-3343",
    "AEP-3695": "[AI] Agent responses are stored to the DB",
    "AEP-3722": "[AI] Add tests for AI service",
    "AEP-3738": "[FE] Allow agent to persist through page changes",
    "AEP-3780": "Integrate with Braintrust (BT)",
    "AEP-3781": "setup datasets in BT",
    "AEP-3782": "develop test for tool use in BT",
    "AEP-3921": "[FE] Allow Sidepanel to expand fullscreen",
    "AEP-3988": "Agent generates entity tags in response",
    "AEP-4033": "[BE] Support intake form sending through mcp",
    "AEP-4051": "[Milestone 2] Backend Auditing",
    "AEP-4052": "Add an auditing datamodel for Via tool calls. Should include toolname, input, related entity, a request ID, and other raw json like outcome or something?",
    "AEP-4105": "Via: In the non-working initial chat interface, hovering over the chat icon displays a hand cursor instead of the default arrow cursor",
    "AEP-4106": "Via: On the Supplier Details page, the sticky header is not aligned properly. The partner program name and supplier images are not fully visible and are overlapping",
    "AEP-4123": "Refreshing messages rehydrates entities",
    "AEP-4124": "[Milestone 2] Tool Approvals",
    "AEP-4125": "Agent can answer questions that dont use or need tools",
    "AEP-4126": "It would be nice to have a tooltip",
    "AEP-4127": "Via icon not visible at top of page but remains clickable on supplier booking details and write a review pages",
    "AEP-4128": "[Milestone 2] Handle message compaction / handle context window more intelligently",
    "AEP-4175": "Via - Mobile: the size of Via icon should be the same size as other icons.",
    "AEP-4185": "[FE] Via: Bookings section becomes misaligned when via section is expanded on dashboard page",
    "AEP-4186": "Via: Side navigation becomes blank after expanding and collapsing via section in account page",
    "AEP-4224": "Add a table to collect feedback",
    "AEP-4241": "[FE] Add thumbs/up and message for feedback",
    "AEP-4256": "[Milestone 2] Add a help button that takes you to Fia chat",
    "AEP-4257": "Add a help button on FE",
    "AEP-4258": "Get more context on how Fin chat works",
    "AEP-4267": "[Milestone 2] Via Fora tone, guidelines",
    "AEP-4268": "Add initial guideline to prompts",
    "AEP-4269": "Refine guidelines over time with feedback",
    "AEP-4284": "Send metadata to mcp from Via",
    "AEP-4351": 'The "Via Chat" option is not displayed on the Contact page.',
    "AEP-4470": "[Research] Explore code mode approach",
    "AEP-4502": 'Trips Calendar: Upon clicking a trip, the popup opens; however, it overlaps with the "Via Chat" panel',
    "AEP-4525": "Audit all mcp tools",
    "AEP-4537": "Via: Tooltips are hidden behind via chat panel on itinerary attachments and booking details page",
    "AEP-4539": "When creating a quote from the side panel, the Quote Preview page is displayed after creation, but the Via Chat icon is not shown on that page.",
    "AEP-4541": "Decide on technical approach for tool approvals",
    "AEP-4542": "[AI] Handle tool approvals",
    "AEP-4569": "[Milestone 1] QA User Feedback",
    "AEP-4595": "[Milestone 2] Advisor personalization",
    "AEP-4596": "[Milestone 2] Via lowest time to first token: research fastest model",
    "AEP-4597": "[Milestone 2] Message compaction (Duplicate)",
    "AEP-4600": 'On Via, the "+" icon does not trigger any action when clicked.',
    "AEP-4601": "On Via Chat, when a long search term without spaces is entered, it does not wrap properly",
    "AEP-4627": 'On the Contacts page, when the screen is set to 100% zoom and the Via chat panel is open, the Action and "Add Contact" menus are not fully visible',
    "AEP-4629": "When the page content is loading, pressing Ctrl + / does not open or close the Via sidebar. The shortcut only functions after the page has fully loaded.",
    "AEP-4630": "Via chat shortcut activates in background while quick search popup is open causing focus conflict",
    "AEP-4631": "Via chat opens behind side panel when triggered with shortcut on supplier details and deals pages",
    "AEP-4636": "Via - When there is more chat history, there is no scroll option available to view the full chat history.",
    "AEP-4696": "In VIA chat, the search text box does not have a placeholder text.",
    "AEP-4701": "On the Access Delegation page, when the 'Via' is opened, the delete button's tooltip text is getting cut off.",
    "AEP-4706": "[Milestone 1] Add a get endpoint to get all tool info for QA",
    "AEP-4716": "[AI] messages also return feedback",
    "AEP-4797": "[BE] Via: Told to upload files but no upload UI exists",
    "AEP-4798": "Via: Formatting not preserved when copying output to Gmail",
    "AEP-4801": "[BE] Was told that it could check hotel live availability even though it cannot do that",
    "AEP-4803": "[BE] If i ask for hotel recs, via should show me a few hotel cards I can click into",
    "AEP-4805": '[FE] Add fun randomized travel words for "Thinking" like Claude does',
    "AEP-4806": "User should be able to delete past chats",
    "AEP-4808": "[BE] Via: Creates new trip instead of adding to existing trip with same destination",
    "AEP-4810": '[FE] Via: "0d" age badge should display "Today" instead',
    "AEP-4811": "[BE] Via: Cannot update status on multiple contacts",
    "AEP-4812": "[FE] Via: Loading animation color sequence feels off-brand",
    "AEP-4813": "Via: /clear clears context but chat messages persist in UI",
    "AEP-4814": "Via: Can generate SVG/image code — should render or be blocked",
    "AEP-4815": "[FE] Via: Drawer should close when a link is clicked and navigates to a new page",
    "AEP-4817": "[FE] Via: Help modal title position inconsistent with other Portal modals",
    "AEP-4819": "[FE] Via: Drawer should close when clicking outside of it",
    "AEP-4820": "Via: Allow advisors to delete chats from history",
    "AEP-4822": "[FE] consider removing Via icon when open",
    "AEP-4823": "[AI] Via: No safeguards on bulk actions (e.g. can create 100 clients at once)",
    "AEP-4824": "[BE] Via: Response latency too high for simple prompts",
    "AEP-4826": '[FE] Via: History icon label is confusing — should be called "Chats"',
    "AEP-4827": "Via: Commission breakdown is more granular than what's shown on the trip page",
    "AEP-4828": "[FE] Via: Input box shifts/resizes when typing a long message — feels disruptive",
    "AEP-4829": "[FE] Text in textbox is off center on mobile",
    "AEP-4833": "[FE] Let's change the default width of via to 400px and see if it makes people happy!",
    "AEP-4837": "Update the text box to have outline and a color bleed shadow outline when you are typing",
    "AEP-4839": "Make the \"What can Via Do\" button smaller. Padding = (8 left/right and 4 top bottom). Total height = 32px",
    "AEP-4841": "Feedback is still available if you get an error",
    "AEP-4842": "Would love to be able to name a chat",
    "AEP-4874": "Would love to be able to name a chat",
    "AEP-4875": "[Milestone 3] Create internal Fora knowledge base for Via assistant",
    "AEP-4881": "Destination knowledge??",
    "AEP-4892": "Set up Google service account to read programmatically from GDrive",
    "AEP-4893": "Write Python functions to import GDrive data using service account",
    "AEP-4894": "Ingest data from Intercom API",
    "AEP-5006": "[BE] Via: Response length is too long and overwhelming",
    "AEP-5015": "Add the agent, Structured Output, Model",
    "AEP-5016": "Add prompt",
    "AEP-5017": "Service to generate summary",
    "AEP-5018": "New table to track message to summary",
    "AEP-5019": "Document how summaries are generated",
    "AEP-5028": "Update Via table",
    "AEP-5029": "Read summaries as part of conversation history",
    "AEP-5036": "[Beta Release Blocking - Infra] Block merges with linting and unit tests",
    "AEP-5037": "[Beta Release Blocking - Infra] Add ai-v2 to deployment script",
    "AEP-5050": "Next Steps not updating",
    "AEP-5066": "Test suite is failing",
    "AEP-5068": "Database connection across the app is inconsistent",
    "AEP-5092": "[Milestone 2] Add a stop button while generating",
    "AEP-5138": "AI: ability to write/update client loyalty numbers via API",
    "AEP-5140": "Fora Ops Evals: datasets and scorer",
    "AEP-5272": "Via trip creation tool rejects valid reason slug 'other'",
    "AEP-5273": "Via cannot identify 'most upcoming' trip when no confirmed start/end dates exist",
    "AEP-5276": "Better Via Observability",
    "AEP-5277": "[BE] Monitoring for the MCP endpoint",
    "AEP-5278": "[AI] Monitoring for existing Via endpoints",
    "AEP-5279": "[AI] Via /conversations/{id}/chat streaming api does not register as an error in DD when errors are thrown",
    "AEP-5280": "[Infra] Via Dashboard - include BE and AI sides",
    "AEP-5281": "[AI] We are able to track costs for via by advisor [Deprioritizing]",
    "AEP-5356": "POC work",
    "AEP-5357": "Web search - Firecrawl",
    "AEP-5360": "Fin Api Agent help center",
    "AEP-5368": "Knowledge base using Weaviate",
    "AEP-5369": "Knowledge base using Turbo puffer",
    "AEP-5370": "Knowledge base using Neo4J",
    "AEP-5373": "Via: Summarize tool call results",
    "AEP-5384": "Knowledge base using Glean",
    "AEP-5446": "POC: Add Booking Platform actions as tools",
    "AEP-5447": "POC: Add Itinerary actions as tools",
}

def escape_js(s):
    """Escape a string for use inside a JS single-quoted string."""
    return s.replace("\\", "\\\\").replace("'", "\\'")

def replace_summary(content, key, new_summary):
    escaped = escape_js(new_summary)
    # Match: key: 'AEP-XXXX' followed (on same line) by summary: '...'
    # JS single-quoted string with possible \' escapes inside
    pattern = (
        rf"(key: '{re.escape(key)}'[^\n]*?summary: ')"
        r"((?:[^'\\]|\\.)*)"
        r"(')"
    )
    repl = rf"\g<1>{escaped}\g<3>"
    new_content, n = re.subn(pattern, repl, content)
    if n == 0:
        print(f"  WARNING: no match for {key}", file=sys.stderr)
    return new_content

path = "index.html"
with open(path) as f:
    content = f.read()

changed = 0
for key, summary in JIRA.items():
    new_content = replace_summary(content, key, summary)
    if new_content != content:
        changed += 1
    content = new_content

with open(path, "w") as f:
    f.write(content)

print(f"Updated {changed} summaries in {path}")
